version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: smartplanner-backend-prod
    # avoid downtime by restarting the container if it crashes (unhandled exceptions/out of memory etc.)
    # app stays dead without restart: always, and need manual SSH to the instance to restart the container
    restart: always
    stop_grace_period: 30s
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - smartplanner

networks:
  # define a custom network for the services to containers to reach each other
  smartplanner:
    name: smartplanner
    driver: bridge
